// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://batmhsckhgalphapwswu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdG1oc2NraGdhbHBoYXB3c3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjExMzQsImV4cCI6MjA3MTkzNzEzNH0.rIp7iKx9AaD6iu-xg3AnhzjFuN4cW0EEmDA0-tme8iE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});